language: java
jdk:
  - oraclejdk8
  
sudo: true

before_install: chmod +x ./buildEnvironment.sh
  
install: sudo ./buildEnvironment.sh

before_script:
  # Install local dependency artifacts
  - mvn install:install-file -Dfile=./fprj-core/libs/as3commons-reflect.swc -DgroupId=net.fproject.as3commons -DartifactId=as3commons-reflect -Dversion=1.0 -Dpackaging=swc
  # Manually install FlexUnit 4.1 locally
  - mvn install:install-file -Dfile=./libs/flexunit-4.1.0-8-flex_4.1.0.16076.swc -DgroupId=com.adobe.flexunit -DartifactId=flexunit -Dversion=4.1.0-8 -Dpackaging=swc
  # Manually install Mockito-Flex 1.4M5 locally
  - mvn install:install-file -Dfile=./libs/mockito-flex-1.4M5.swc -DgroupId=org.mockito -DartifactId=mockito-flex -Dversion=1.4M5 -Dpackaging=swc

script: 
  - cp pom.xml fprj-core-test/ && cd fprj-core-test
  - mvn -e test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - libnss3
      - libgtk2.0-dev
      - libnotify-dev
      - libdbus-1-dev
      - libxrandr-dev
      - libxext-dev
      - libxss-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libcurl4-openssl-dev 
      - libxkbfile-dev
      - xauth 
      - xorg
