language: java
jdk:
  - oraclejdk8
  
sudo: true

before_install: chmod +x ./buildEnvironment.sh
  
install: sudo ./buildEnvironment.sh

script: xvfb gradle test

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - xvfb
      - libnss3
      - libgtk2.0-dev
      - libnotify-dev
      - libdbus-1-dev
      - libxrandr-dev
      - libxext-dev
      - libxss-dev
      - libgconf2-dev
      - libasound2-dev
      - libcap-dev
      - libcups2-dev
      - libXtst-dev
      - libcurl4-openssl-dev 
      - libxkbfile-dev
      - xauth 
      - xorg
